[pytest]
testpaths =
    m2_motor/tests
    m3_sensors/tests
    m4_vision/tests
    m5_navigation/tests
    m6_decision/tests
    m7_logging/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
